### PR TITLE
Remove Nuxt from project

### PR DESCRIPTION
**Pull request by TanyaKulikovskaya**

### CODE REVIEW

**Review by Klimonov — COMMENTED** [review]
what a version of nodejs you have ?

**Comment by TanyaKulikovskaya** [comment]
@Klimonov v16.13

**Review by Klimonov — APPROVED** [review]
LGTM

**Comment by kezlya** [comment]
@TanyaKulikovskaya is this still `WIP` ? or we can merge it ?

**Comment by TanyaKulikovskaya** [comment]
@kezlya It's still WIP

**Comment by Klimonov** [comment]
@kezlya my LGTM was demonstrative when I explained the github flow. Deleted

**Review by EgoriusRus — APPROVED** [review]
LGTM
Good work!

**Pull request merged**
